//===============================================================================
// Microsoft patterns & practices
// Web Service Software Factory
//===============================================================================
// Copyright � Microsoft Corporation.  All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE.
//===============================================================================
// The example companies, organizations, products, domain names,
// e-mail addresses, logos, people, places, and events depicted
// herein are fictitious.  No association with any real company,
// organization, product, domain name, email address, logo, person,
// places, or events is intended or should be inferred.
//===============================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.ServiceFactory.HostDesigner
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "host";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"Web Service Software Factory: Modeling Edition";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Microsoft PLK";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID HostDesignerDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(HostDesignerCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID HostDesignerExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(HostDesignerCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewHostDesignerExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(HostDesignerCommandSetId), 0x0001);
	
		// Package identifier
		public const string HostDesignerPackageId = "433e3a20-4740-4938-8c81-adf28d430188";
		
		// Editor factory identifier
		public const string HostDesignerEditorFactoryId = "dfb1660d-4c34-42fd-9d56-52e6c33cec4c";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string HostDesignerModelExplorerToolWindowId = "af1944ad-4b19-4ee6-9f7c-01f71e5b8c26";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Microsoft.Practices.ServiceFactory.HostDesigner
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string HostDesignerCommandSetId = "7f1c6863-602e-41c8-8509-a8647dd25d3b";
	}
}