//===============================================================================
// Microsoft patterns & practices
// Web Service Software Factory
//===============================================================================
// Copyright � Microsoft Corporation.  All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE.
//===============================================================================
// The example companies, organizations, products, domain names,
// e-mail addresses, logos, people, places, and events depicted
// herein are fictitious.  No association with any real company,
// organization, product, domain name, email address, logo, person,
// places, or events is intended or should be inferred.
//===============================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

namespace Microsoft.Practices.ServiceFactory.HostDesigner
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	internal partial class HostDesignerExplorer : HostDesignerExplorerBase
	{
		/// <summary>
		/// Constructs a new HostDesignerExplorer.
		/// </summary>
		public HostDesignerExplorer(global::System.IServiceProvider serviceProvider)
			: base(serviceProvider)
		{
		}
	}
	
	/// <summary>
	/// Control hosted in the HostDesignerExplorerToolWindow.
	/// </summary>
	internal abstract class HostDesignerExplorerBase : DslShell::ModelExplorerTreeContainer
	{
		/// <summary>
		/// Constructs a new HostDesignerExplorerBase.
		/// </summary>
		protected HostDesignerExplorerBase(global::System.IServiceProvider serviceProvider) : base(serviceProvider)
		{
			
			
			// Adds custom tree node settings...
			global::System.Resources.ResourceManager resourceManager = global::Microsoft.Practices.ServiceFactory.HostDesigner.HostDesignerDomainModel.SingletonResourceManager;
			
			this.AddExplorerNodeCustomSetting(global::Microsoft.Practices.ServiceFactory.HostDesigner.ClientApplication.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ClientApplicationExplorerImage")), 
							false); 
			this.AddExplorerNodeCustomSetting(global::Microsoft.Practices.ServiceFactory.HostDesigner.Proxy.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ProxyExplorerImage")), 
							false); 
			this.AddExplorerNodeCustomSetting(global::Microsoft.Practices.ServiceFactory.HostDesigner.HostApplication.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("HostApplicationExplorerImage")), 
							false); 
			this.AddExplorerNodeCustomSetting(global::Microsoft.Practices.ServiceFactory.HostDesigner.ServiceReference.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ServiceReferenceExplorerImage")), 
							false); 
			this.AddExplorerNodeCustomSetting(global::Microsoft.Practices.ServiceFactory.HostDesigner.Endpoint.DomainClassId, 
							DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EndpointExplorerImage")), 
							false); 
		}
	
	
	
		/// <summary>
		/// Create IElementVisitor
		/// </summary>
		/// <returns>IElementVisitor</returns>
		protected override DslModeling::IElementVisitor CreateElementVisitor()
		{
			return new DslShell::ExplorerElementVisitor(this);
		}
	
		/// <summary>
		/// Specifies the context menu that should be shown for the model explorer.
		///</summary>
		protected override global::System.ComponentModel.Design.CommandID ContextMenuCommandId
		{
			get
			{
				return Constants.HostDesignerExplorerMenu;
			}
		}
		
		/// <summary>
		/// Returns the root elements domain class Id. The is the very top level tree node in the TreeView
		///</summary>
		protected override global::System.Guid RootElementDomainClassId
		{
			get { return global::Microsoft.Practices.ServiceFactory.HostDesigner.HostDesignerModel.DomainClassId; }
		}
		
		/// <summary>
		/// Returns the root elements to be displayed in the explorer.
		///</summary>
		protected override global::System.Collections.IList FindRootElements(DslModeling::Store store)
		{
			return store.ElementDirectory.FindElements( this.RootElementDomainClassId);
		}
	}
}
	


