//===============================================================================
// Microsoft patterns & practices
// Web Service Software Factory
//===============================================================================
// Copyright � Microsoft Corporation.  All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE.
//===============================================================================
// The example companies, organizations, products, domain names,
// e-mail addresses, logos, people, places, and events depicted
// herein are fictitious.  No association with any real company,
// organization, product, domain name, email address, logo, person,
// places, or events is intended or should be inferred.
//===============================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.ServiceFactory.DataContracts
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "datacontract";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"Web Service Software Factory: Modeling Edition";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Microsoft PLK";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID DataContractDslDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DataContractDslCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID DataContractDslExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DataContractDslCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewDataContractDslExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DataContractDslCommandSetId), 0x0001);
	
		// Package identifier
		public const string DataContractDslPackageId = "1a168a56-ee16-4520-a071-3431a82d3e1f";
		
		// Editor factory identifier
		public const string DataContractDslEditorFactoryId = "8a145541-905e-48df-8b48-640b4db62c9d";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string DataContractDslModelExplorerToolWindowId = "6c7b7cdc-4211-44b5-81ce-e25ed336fe80";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Microsoft.Practices.ServiceFactory.DataContracts
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string DataContractDslCommandSetId = "44157ffb-0ae0-44e4-858c-366754e3dcc9";
	}
}