
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//
// This file contains generated default command definitions.
// Additional command definitions should be added to CustomCmd.ctc.
//

///////////////////////////////////////////////////////////////////////////////
// CTC command IDs - MUST be kept in sync with Constants.cs

#define menuidContext		0x10000
#define grpidContextMain	0x20000
#define menuidExplorer		0x10001
#define cmdidViewExplorer	0x0001

///////////////////////////////////////////////////////////////////////////////
// CTC macros

#define OI_NOID		guidOfficeIcon:msotcidNoIcon
#define DIS_DEF		DEFAULTDISABLED | DEFAULTINVISIBLE | DYNAMICVISIBILITY
#define VIS_DEF		COMMANDWELLONLY	

///////////////////////////////////////////////////////////////////////////////
// Menu definitions

#define GENERATED_MENUS \
	guidCmdSet:menuidContext, guidCmdSet:menuidContext,	0x0000,	CONTEXT|ALWAYSCREATE, "Data Contract Model Designer Context Menu", "DataContractDsl Context"; \
	guidCmdSet:menuidExplorer, guidCmdSet:menuidExplorer, 0x0000, CONTEXT|ALWAYSCREATE, "Data Contract Model Explorer Context Menu", "Data Contract Explorer"; \

///////////////////////////////////////////////////////////////////////////////
// Group definitions

#define GENERATED_GROUPS \
	guidCmdSet:grpidContextMain, guidCmdSet:grpidContextMain,	0x0010; \


///////////////////////////////////////////////////////////////////////////////
// Command definitions

#define GENERATED_BUTTONS \
	guidCmdSet:cmdidViewExplorer, guidSHLMainMenu:IDG_VS_WNDO_OTRWNDWS1, 0x0100,	OI_NOID, BUTTON, DIS_DEF, "Data Contract Explorer";


///////////////////////////////////////////////////////////////////////////////
// Command placement definitions

#define GENERATED_CMDPLACEMENT \
	guidVSStd97:cmdidDelete, guidCmdSet:grpidContextMain, 0x0010; \
	guidSHLMainMenu:IDG_VS_CTXT_SOLUTION_PROPERTIES, guidCmdSet:menuidContext, 0x0500; \
	guidCmdSet:grpidContextMain, guidCmdSet:menuidContext, 0x0010; \
	guidCommonModelingMenu:grpidCompartmentShapeMenuGroup, guidCmdSet:menuidContext, 0x0008; \
	guidCommonModelingMenu:grpidSwimlaneShapeMenuGroup, guidCmdSet:menuidContext, 0x0008; \
	guidCommonModelingMenu:grpidValidateCommands, guidCmdSet:menuidContext, 0x0020; \
	guidCommonModelingMenu:grpidLayoutMenuGroup, guidCmdSet:menuidContext, 0x0030; \
	guidCommonModelingMenu:grpidExplorerMenuGroup, guidCmdSet:menuidExplorer, 0x0010; \
	guidSHLMainMenu:IDG_VS_CTXT_SOLUTION_PROPERTIES, guidCmdSet:menuidExplorer, 0x0020; \
	guidCommonModelingMenu:grpidValidateCommands, guidCmdSet:menuidExplorer, 0x0030; \
    

///////////////////////////////////////////////////////////////////////////////
// Command visibility definitions

#define GENERATED_VISIBILITY \
	guidCmdSet:cmdidViewExplorer, guidEditor; \

///////////////////////////////////////////////////////////////////////////////
// CTC guids - MUST be kept in sync with GeneratedCmd.cs

#define guidPkg			{ 0x1a168a56, 0xee16, 0x4520, { 0xa0, 0x71, 0x34, 0x31, 0xa8, 0x2d, 0x3e, 0x1f } }
#define guidEditor		{ 0x8a145541, 0x905e, 0x48df, { 0x8b, 0x48, 0x64, 0x0b, 0x4d, 0xb6, 0x2c, 0x9d } }


#define guidCmdSet		{ 0x44157ffb, 0x0ae0, 0x44e4, { 0x85, 0x8c, 0x36, 0x67, 0x54, 0xe3, 0xdc, 0xc9 } }
