//===============================================================================
// Microsoft patterns & practices
// Web Service Software Factory
//===============================================================================
// Copyright � Microsoft Corporation.  All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE.
//===============================================================================
// The example companies, organizations, products, domain names,
// e-mail addresses, logos, people, places, and events depicted
// herein are fictitious.  No association with any real company,
// organization, product, domain name, email address, logo, person,
// places, or events is intended or should be inferred.
//===============================================================================

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

namespace Microsoft.Practices.ServiceFactory.DataContracts
{
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	/// <remarks>
	/// Double-derived class to allow easier code customization.
	/// </remarks>
	public partial class DataContractDslToolboxHelper : DataContractDslToolboxHelperBase 
	{
		/// <summary>
		/// Constructs a new DataContractDslToolboxHelper.
		/// </summary>
		public DataContractDslToolboxHelper(global::System.IServiceProvider serviceProvider)
			: base(serviceProvider) { }
	}
	
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	public abstract class DataContractDslToolboxHelperBase
	{
		/// <summary>
		/// Toolbox item filter string used to identify DataContractDsl toolbox items.  
		/// </summary>
		/// <remarks>
		/// See the MSDN documentation for the ToolboxItemFilterAttribute class for more information on toolbox
		/// item filters.
		/// </remarks>
		public const string ToolboxFilterString = "DataContractDsl.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify AggregationConnectionTool connector tool.
		/// </summary>
		public const string AggregationConnectionToolFilterString = "AggregationConnectionTool.1.0";

		private global::System.IServiceProvider sp;
		
		/// <summary>
		/// Constructs a new DataContractDslToolboxHelperBase.
		/// </summary>
		protected DataContractDslToolboxHelperBase(global::System.IServiceProvider serviceProvider)
		{
			if(serviceProvider == null) throw new global::System.ArgumentNullException("serviceProvider");
			
			this.sp = serviceProvider;
		}
		
		/// <summary>
		/// Serivce provider used to access services from the hosting environment.
		/// </summary>
		protected global::System.IServiceProvider ServiceProvider
		{
			get
			{
				return this.sp;
			}
		}

		/// <summary>
		/// Returns the display name of the tab that should be opened by default when the editor is opened.
		/// </summary>
		public static string DefaultToolboxTabName
		{
			get
			{
				return global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractDslDomainModel.SingletonResourceManager.GetString("Data Contract ToolsToolboxTab", global::System.Globalization.CultureInfo.CurrentUICulture);
			}
		}
		
		
		/// <summary>
		/// Returns the toolbox items count in the default tool box tab.
		/// </summary>
		public static int DefaultToolboxTabToolboxItemsCount
		{
			get
			{
				return 6;
			}
		}
		

		/// <summary>
		/// Returns a list of toolbox items for use with this DSL.
		/// </summary>
		public virtual global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem> toolboxItems = new global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem>();
			
			// Create store and load domain models.
			using(DslModeling::Store store = new DslModeling::Store(this.ServiceProvider))
			{
				store.LoadDomainModels(typeof(DslDiagrams::CoreDesignSurfaceDomainModel),
					typeof(global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractDslDomainModel));
				global::System.Resources.ResourceManager resourceManager = global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractDslDomainModel.SingletonResourceManager;
				global::System.Globalization.CultureInfo resourceCulture = global::System.Globalization.CultureInfo.CurrentUICulture;
			
				// Open transaction so we can create model elements corresponding to toolbox items.
				using(DslModeling::Transaction t = store.TransactionManager.BeginTransaction("CreateToolboxItems"))
				{

					// Add DataContractTool shape tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"DataContractToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("DataContractToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("DataContractToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Data Contract ToolsToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("Data Contract ToolsToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"DataContractTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("DataContractToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Microsoft.Practices.ServiceFactory.DataContracts.DataContract.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						}));

					// Add DataContractEnumTool shape tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"DataContractEnumToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("DataContractEnumToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("DataContractEnumToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Data Contract ToolsToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("Data Contract ToolsToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"DataContractEnumTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("DataContractEnumToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractEnum.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						}));

					// Add PrimitiveDataTypeCollectionTool shape tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"PrimitiveDataTypeCollectionToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						3, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("PrimitiveDataTypeCollectionToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("PrimitiveDataTypeCollectionToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Data Contract ToolsToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("Data Contract ToolsToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"PrimitiveDataTypeCollectionTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("PrimitiveDataTypeCollectionToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Microsoft.Practices.ServiceFactory.DataContracts.PrimitiveDataTypeCollection.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						}));

					// Add DataContractCollectionTool shape tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"DataContractCollectionToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						4, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("DataContractCollectionToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("DataContractCollectionToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Data Contract ToolsToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("Data Contract ToolsToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"DataContractCollectionTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("DataContractCollectionToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Microsoft.Practices.ServiceFactory.DataContracts.DataContractCollection.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						}));

					// Add FaultContractTool shape tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"FaultContractToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						5, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("FaultContractToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("FaultContractToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"Data Contract ToolsToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("Data Contract ToolsToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"FaultContractTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("FaultContractToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::Microsoft.Practices.ServiceFactory.DataContracts.FaultContract.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						}));

					// Add AggregationConnectionTool connector tool.
					toolboxItems.Add(new DslDesign::ModelingToolboxItem(
						"AggregationConnectionToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						6, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("AggregationConnectionToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("AggregationConnectionToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"Data Contract ToolsToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("Data Contract ToolsToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"Aggregation", // F1 help keyword for the toolbox item.
						resourceManager.GetString("AggregationConnectionToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(AggregationConnectionToolFilterString)
						}));

					t.Rollback();
				}
			}

			return toolboxItems;
		}
		
		/// <summary>
		/// Creates an ElementGroupPrototype for the element tool corresponding to the given domain class id.
		/// Default behavior is to create a prototype containing an instance of the domain class.
		/// Derived classes may override this to add additional information to the prototype.
		/// </summary>
		protected virtual DslModeling::ElementGroupPrototype CreateElementToolPrototype(DslModeling::Store store, global::System.Guid domainClassId)
		{
			DslModeling::ModelElement element = store.ElementFactory.CreateElement(domainClassId);
			DslModeling::ElementGroup elementGroup = new DslModeling::ElementGroup(store.DefaultPartition);
			elementGroup.AddGraph(element, true);
			return elementGroup.CreatePrototype();
		}
	}
}
