
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//
// This file contains generated default command definitions.
// Additional command definitions should be added to CustomCmd.ctc.
//

///////////////////////////////////////////////////////////////////////////////
// CTC command IDs - MUST be kept in sync with Constants.cs

#define menuidContext		0x10000
#define grpidContextMain	0x20000
#define menuidExplorer		0x10001
#define cmdidViewExplorer	0x0001

///////////////////////////////////////////////////////////////////////////////
// CTC macros

#define OI_NOID		guidOfficeIcon:msotcidNoIcon
#define DIS_DEF		DEFAULTDISABLED | DEFAULTINVISIBLE | DYNAMICVISIBILITY
#define VIS_DEF		COMMANDWELLONLY	

///////////////////////////////////////////////////////////////////////////////
// Menu definitions

#define GENERATED_MENUS \
	guidCmdSet:menuidContext, guidCmdSet:menuidContext,	0x0000,	CONTEXT|ALWAYSCREATE, "Service Contract Model Designer Context Menu", "ServiceContractDsl Context"; \
	guidCmdSet:menuidExplorer, guidCmdSet:menuidExplorer, 0x0000, CONTEXT|ALWAYSCREATE, "Service Contract Model Explorer Context Menu", "Service Contract Explorer"; \

///////////////////////////////////////////////////////////////////////////////
// Group definitions

#define GENERATED_GROUPS \
	guidCmdSet:grpidContextMain, guidCmdSet:grpidContextMain,	0x0010; \


///////////////////////////////////////////////////////////////////////////////
// Command definitions

#define GENERATED_BUTTONS \
	guidCmdSet:cmdidViewExplorer, guidSHLMainMenu:IDG_VS_WNDO_OTRWNDWS1, 0x0100,	OI_NOID, BUTTON, DIS_DEF, "Service Contract Explorer";


///////////////////////////////////////////////////////////////////////////////
// Command placement definitions

#define GENERATED_CMDPLACEMENT \
	guidVSStd97:cmdidDelete, guidCmdSet:grpidContextMain, 0x0010; \
	guidSHLMainMenu:IDG_VS_CTXT_SOLUTION_PROPERTIES, guidCmdSet:menuidContext, 0x0500; \
	guidCmdSet:grpidContextMain, guidCmdSet:menuidContext, 0x0010; \
	guidCommonModelingMenu:grpidCompartmentShapeMenuGroup, guidCmdSet:menuidContext, 0x0008; \
	guidCommonModelingMenu:grpidSwimlaneShapeMenuGroup, guidCmdSet:menuidContext, 0x0008; \
	guidCommonModelingMenu:grpidValidateCommands, guidCmdSet:menuidContext, 0x0020; \
	guidCommonModelingMenu:grpidLayoutMenuGroup, guidCmdSet:menuidContext, 0x0030; \
	guidCommonModelingMenu:grpidExplorerMenuGroup, guidCmdSet:menuidExplorer, 0x0010; \
	guidSHLMainMenu:IDG_VS_CTXT_SOLUTION_PROPERTIES, guidCmdSet:menuidExplorer, 0x0020; \
	guidCommonModelingMenu:grpidValidateCommands, guidCmdSet:menuidExplorer, 0x0030; \
    

///////////////////////////////////////////////////////////////////////////////
// Command visibility definitions

#define GENERATED_VISIBILITY \
	guidCmdSet:cmdidViewExplorer, guidEditor; \

///////////////////////////////////////////////////////////////////////////////
// CTC guids - MUST be kept in sync with GeneratedCmd.cs

#define guidPkg			{ 0x43805256, 0xe844, 0x436e, { 0x88, 0x35, 0x03, 0x5c, 0xc9, 0x72, 0xa4, 0x41 } }
#define guidEditor		{ 0x74a1ee75, 0x1c00, 0x4e23, { 0x9e, 0x74, 0x1e, 0x24, 0xaf, 0x93, 0x4c, 0xfd } }


#define guidCmdSet		{ 0x0cd5c408, 0x18b5, 0x4905, { 0x8e, 0x14, 0xa5, 0x84, 0x04, 0x24, 0x72, 0x20 } }
