//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Practices.ServiceFactory.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Practices.ServiceFactory.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The behavior {0} was not found..
        /// </summary>
        internal static string BehaviorNotFoundException {
            get {
                return ResourceManager.GetString("BehaviorNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The binding {0} was not found..
        /// </summary>
        internal static string BindingNotFoundException {
            get {
                return ResourceManager.GetString("BindingNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} could not be added to the source control system..
        /// </summary>
        internal static string CheckoutException {
            get {
                return ResourceManager.GetString("CheckoutException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies to the client proxy shape..
        /// </summary>
        internal static string ClientProxyShapeReference {
            get {
                return ResourceManager.GetString("ClientProxyShapeReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WCF Code Analysis passed successfully..
        /// </summary>
        internal static string CodeAnalysisSuccess {
            get {
                return ResourceManager.GetString("CodeAnalysisSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WCF Code Analysis detected {0} rule warnings. Please see detailed information in the Error List window..
        /// </summary>
        internal static string CodeAnalysisWarnings {
            get {
                return ResourceManager.GetString("CodeAnalysisWarnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Contract Model.
        /// </summary>
        internal static string DataContractModelImageText {
            get {
                return ResourceManager.GetString("DataContractModelImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The schema &apos;{0}&apos; is a DataSet and is not allowed for this operation..
        /// </summary>
        internal static string DataSetSchemaNotAllowed {
            get {
                return ResourceManager.GetString("DataSetSchemaNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DomainModel for the model element &apos;{0}&apos; was not found..
        /// </summary>
        internal static string DomainModelNotFound {
            get {
                return ResourceManager.GetString("DomainModelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies to DSL Surface Area..
        /// </summary>
        internal static string DSLSurfaceArea {
            get {
                return ResourceManager.GetString("DSLSurfaceArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total generated elements: {0}.
        /// </summary>
        internal static string ElementsGenerated {
            get {
                return ResourceManager.GetString("ElementsGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorMsgBoxTitle {
            get {
                return ResourceManager.GetString("ErrorMsgBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated objects: {0}.
        /// </summary>
        internal static string GeneratedObjects {
            get {
                return ResourceManager.GetString("GeneratedObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceContract model elements.
        /// </summary>
        internal static string GeneratingServiceContractsMessage {
            get {
                return ResourceManager.GetString("GeneratingServiceContractsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Model.
        /// </summary>
        internal static string HostDesignerModelImageText {
            get {
                return ResourceManager.GetString("HostDesignerModelImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model host application, service endpoints, and client/proxies..
        /// </summary>
        internal static string HostModelDescription {
            get {
                return ResourceManager.GetString("HostModelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string IdleStatusBarMessage {
            get {
                return ResourceManager.GetString("IdleStatusBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing {0} ....
        /// </summary>
        internal static string ImportingElements {
            get {
                return ResourceManager.GetString("ImportingElements", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Information {
            get {
                object obj = ResourceManager.GetObject("Information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot perform mapping between {0} and {1}. Possible reasons are incompatible types or unavailable getter/setter pairs..
        /// </summary>
        internal static string InvalidMappingErrorMessage {
            get {
                return ResourceManager.GetString("InvalidMappingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Property Mapping.
        /// </summary>
        internal static string InvalidMappingErrorTitle {
            get {
                return ResourceManager.GetString("InvalidMappingErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid namespace.
        /// </summary>
        internal static string InvalidNamespaceError {
            get {
                return ResourceManager.GetString("InvalidNamespaceError", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap LargeIcons {
            get {
                object obj = ResourceManager.GetObject("LargeIcons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log error.
        /// </summary>
        internal static string LogErrorTitle {
            get {
                return ResourceManager.GetString("LogErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log information.
        /// </summary>
        internal static string LogInformationTitle {
            get {
                return ResourceManager.GetString("LogInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} {2}.
        /// </summary>
        internal static string MappedPropertyToString {
            get {
                return ResourceManager.GetString("MappedPropertyToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model data and fault contracts..
        /// </summary>
        internal static string MessageModelDescription {
            get {
                return ResourceManager.GetString("MessageModelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation &apos;{0}&apos; has no FaultContract defined for validation. Add the  [FaultContract(typeof(ValidationFault))] attribute to this operation. .
        /// </summary>
        internal static string MissingFaultDescription {
            get {
                return ResourceManager.GetString("MissingFaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies to a Model Project..
        /// </summary>
        internal static string ModelProjectReference {
            get {
                return ResourceManager.GetString("ModelProjectReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view.Endpoint.Binding property has an empty value..
        /// </summary>
        internal static string NullBindingException {
            get {
                return ResourceManager.GetString("NullBindingException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view.Endpoint property has an empty value..
        /// </summary>
        internal static string NullEndpointException {
            get {
                return ResourceManager.GetString("NullEndpointException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order All DataMembers reference.
        /// </summary>
        internal static string OrderAllDataMembersReference {
            get {
                return ResourceManager.GetString("OrderAllDataMembersReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordered &apos;{1}&apos; items on the &apos;{0}&apos; element..
        /// </summary>
        internal static string OrderedDataMembers {
            get {
                return ResourceManager.GetString("OrderedDataMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current selected model contains elements. Are you sure you want to import ? .
        /// </summary>
        internal static string OverwriteExistingModel {
            get {
                return ResourceManager.GetString("OverwriteExistingModel", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap p_p {
            get {
                object obj = ResourceManager.GetObject("p_p", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project with a particular role.
        /// </summary>
        internal static string ProjectIsInRoleReference {
            get {
                return ResourceManager.GetString("ProjectIsInRoleReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected name is invalid..
        /// </summary>
        internal static string ProjectItemInvalidName {
            get {
                return ResourceManager.GetString("ProjectItemInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected name is already exists in the project..
        /// </summary>
        internal static string ProjectItemNameAlreadyExists {
            get {
                return ResourceManager.GetString("ProjectItemNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Proyect Mapping Table file was not found or the Proyect Mapping Table value specified in this model does not exists..
        /// </summary>
        internal static string ProjectMappingTableException {
            get {
                return ResourceManager.GetString("ProjectMappingTableException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;Project&apos; was not assigned. Specify a value for the &apos;Project&apos; property where the generated code should be placed..
        /// </summary>
        internal static string ProjectPropertyNotAssigned {
            get {
                return ResourceManager.GetString("ProjectPropertyNotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties for {0}.
        /// </summary>
        internal static string PropertiesLabelText {
            get {
                return ResourceManager.GetString("PropertiesLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        internal static string PublicPropertyListItemToString {
            get {
                return ResourceManager.GetString("PublicPropertyListItemToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an importer file.
        /// </summary>
        internal static string SelectImporterFile {
            get {
                return ResourceManager.GetString("SelectImporterFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model service contracts, operations, and messages..
        /// </summary>
        internal static string ServiceModelDescription {
            get {
                return ResourceManager.GetString("ServiceModelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Contract Model.
        /// </summary>
        internal static string ServiceModelImageText {
            get {
                return ResourceManager.GetString("ServiceModelImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Factory: Modeling Edition.
        /// </summary>
        internal static string ServiceSoftwareFactory {
            get {
                return ResourceManager.GetString("ServiceSoftwareFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service location is invalid. Select a valid location as a file path or service URL..
        /// </summary>
        internal static string ServiceUriValidationMessage {
            get {
                return ResourceManager.GetString("ServiceUriValidationMessage", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap SF {
            get {
                object obj = ResourceManager.GetObject("SF", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies to a particular MEL with artifact links..
        /// </summary>
        internal static string ShapeHasArtifactLinksReference {
            get {
                return ResourceManager.GetString("ShapeHasArtifactLinksReference", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap SmallIcons {
            get {
                object obj = ResourceManager.GetObject("SmallIcons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies to Solution Folders that contains projects..
        /// </summary>
        internal static string SolutionFolderHasProjectsReference {
            get {
                return ResourceManager.GetString("SolutionFolderHasProjectsReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies to a Solution..
        /// </summary>
        internal static string SolutionReference {
            get {
                return ResourceManager.GetString("SolutionReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose two different types to translate between..
        /// </summary>
        internal static string TranslatedTypesMustBeDifferent {
            get {
                return ResourceManager.GetString("TranslatedTypesMustBeDifferent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; was created or updated..
        /// </summary>
        internal static string UpdatedFile {
            get {
                return ResourceManager.GetString("UpdatedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were validation errors. Check the error list window and fix the errors and run this recipe again..
        /// </summary>
        internal static string ValidationException {
            get {
                return ResourceManager.GetString("ValidationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This WSDL has the following warning:\n\r{0}\n\rDo you want to continue with the import?.
        /// </summary>
        internal static string ValidationWarnings {
            get {
                return ResourceManager.GetString("ValidationWarnings", resourceCulture);
            }
        }
    }
}
