//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.PowerCommands.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.PowerCommands.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create window.
        /// </summary>
        internal static string CannotCreateToolwindow {
            get {
                return ResourceManager.GetString("CannotCreateToolwindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity should be &gt; 0.
        /// </summary>
        internal static string CapacityShouldBeGreaterThanZero {
            get {
                return ResourceManager.GetString("CapacityShouldBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command will delete all entries on your recent list. Do you want to proceed?.
        /// </summary>
        internal static string ClearRecentList {
            get {
                return ResourceManager.GetString("ClearRecentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty stack.
        /// </summary>
        internal static string EmptyStack {
            get {
                return ResourceManager.GetString("EmptyStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration ended.
        /// </summary>
        internal static string EnumEnded {
            get {
                return ResourceManager.GetString("EnumEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration not started.
        /// </summary>
        internal static string EnumNotStarted {
            get {
                return ResourceManager.GetString("EnumNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred when trying to launch the default mail client..
        /// </summary>
        internal static string ExceptionLaunchingDefaultMailClient {
            get {
                return ResourceManager.GetString("ExceptionLaunchingDefaultMailClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently closed documents.
        /// </summary>
        internal static string RecentlyClosedDocuments {
            get {
                return ResourceManager.GetString("RecentlyClosedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to restart Visual Studio to apply the changes. Do you want to restart it now?.
        /// </summary>
        internal static string RestartVS {
            get {
                return ResourceManager.GetString("RestartVS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transforming template {0} with {1} ... succeeded.
        /// </summary>
        internal static string TransformTemplateMessage {
            get {
                return ResourceManager.GetString("TransformTemplateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error transforming template {0}.
        /// </summary>
        internal static string TransformTemplateMessageError {
            get {
                return ResourceManager.GetString("TransformTemplateMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item {0} is readonly..
        /// </summary>
        internal static string TransformTemplateReadOnly {
            get {
                return ResourceManager.GetString("TransformTemplateReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Close.
        /// </summary>
        internal static string UndoCloseCaption {
            get {
                return ResourceManager.GetString("UndoCloseCaption", resourceCulture);
            }
        }
    }
}
